## tests/test_manifest.nim — packaging.
##
## `coworld_manifest_template.json` is generated by `tools/build_manifest.py`,
## so this file asserts the CONTRACT rather than the formatting: the seat count
## everywhere, the image placeholder derived from compose.yaml's service name,
## the secret namespace equal to `game.name`, the docs and both protocols, the
## schema bounds, and the certification fixture's arithmetic.

import std/[json, os, strutils]
import support/helpers
import hidden_agenda/[sim_types, sim_config, sim, scripted]

template check(condition: bool, message: string) =
  if not condition:
    echo "FAIL: ", message
    quit(1)

const RepoRoot = currentSourcePath().parentDir().parentDir()

let manifest = parseFile(RepoRoot / "coworld_manifest_template.json")
let compose = readFile(RepoRoot / "compose.yaml")
let game = manifest{"game"}

block imagePlaceholderComesFromCompose:
  ## `services.hidden_agenda` -> {{HIDDEN_AGENDA_IMAGE}}. `coworld build`
  ## derives the placeholder from the COMPOSE SERVICE NAME and hard-fails
  ## anything else; {{GAME_IMAGE}} is not a thing (lantern 0.1.0, 2026-08-23).
  var service = ""
  var inServices = false
  for raw in compose.splitLines():
    if raw.startsWith("services:"):
      inServices = true
      continue
    if not inServices:
      continue
    if raw.len > 2 and raw[0] == ' ' and raw[1] == ' ' and raw[2] != ' ' and
        raw.strip().endsWith(":"):
      check(service.len == 0, "compose.yaml must declare exactly one service")
      service = raw.strip().strip(chars = {':'})
  check(service.len > 0, "compose.yaml must declare a service")
  let want = "{{" & service.toUpperAscii() & "_IMAGE}}"
  check(game{"runnable"}{"image"}.getStr() == want,
    "the image placeholder must be " & want & ", got " &
    game{"runnable"}{"image"}.getStr())
  check(game{"name"}.getStr() == service,
    "game.name must equal the compose service name")
  check(game{"name"}.getStr() == GameName,
    "and the name the sim compiles with")

block secretNamespaceIsGameName:
  ## The secret namespace must equal `game.name` EXACTLY, or upload 400s
  ## "Coworld secret <ns> cannot be used by Coworld" after a fully green
  ## certify (cooperative-hunting, 2026-08-25).
  let uri = game{"runnable"}{"env"}{"ANTHROPIC_API_KEY_URI"}.getStr()
  check(uri == "secret://coworld/" & game{"name"}.getStr() &
    "/anthropic_api_key",
    "the game runnable must carry the coworld secret URI, got '" & uri & "'")

block seatCountEverywhere:
  let variants = manifest{"variants"}
  check(variants.len == 3, "three variants")
  for variant in variants:
    check(variant{"game_config"}{"num_agents"}.getInt() == Seats,
      "num_agents must be " & $Seats & " in variant " &
      variant{"id"}.getStr())
    check(variant{"description"}.getStr().len > 0,
      "every variant needs a description")
    check(variant{"game_config"}{"players"}.len == Seats,
      "every variant seats five players")
  let cert = manifest{"certification"}
  check(cert{"game_config"}{"num_agents"}.getInt() == Seats,
    "num_agents must be in the certification fixture too")
  check(cert{"players"}.len == Seats, "the fixture seats five")
  check(cert{"game_config"}{"players"}.len == Seats,
    "and names five players")

block everyDeclaredPlayerIsSeated:
  ## Cert `players-run` fails `players_missing` the moment a declared player
  ## entry has no certification slot (raid 0.1.2 -> 0.1.3).
  var seated: seq[string]
  for row in manifest{"certification"}{"players"}:
    seated.add(row{"player_id"}.getStr())
  check(manifest{"player"}.len == 2, "exactly two declared player entries")
  for entry in manifest{"player"}:
    let id = entry{"id"}.getStr()
    check(id in seated, "player entry " & id & " has no certification slot")
    check(entry{"type"}.getStr() == "player", id & " must be type player")
    check(entry{"name"}.getStr().len > 0, id & " needs a name")
    check(entry{"description"}.getStr().len > 0, id & " needs a description")
    check(entry{"run"}.len >= 1, id & " needs a run argv")
    check(entry{"env"}.len >= 1, id & " needs its PLAYER_SCRIPTED env")

block replayViewerIsAStaticBundle:
  check(game{"replay_viewer"}{"bundle"}.getStr() == "static-replay-viewer",
    "the replay viewer is the STATIC bundle, never a pod")

  ## ...and there is no pod path serving a replay page ANYWHERE: not a route,
  ## not a handler, not a sentence in a doc, not a line of the manifest the
  ## platform renders. The static bundle is the only replay surface.
  var offenders: seq[string]
  for dir in ["src", "docs", "client"]:
    for path in walkDirRec(RepoRoot / dir):
      if path.endsWith(".nim") or path.endsWith(".md") or
          path.endsWith(".html"):
        if "/client/replay" in readFile(path):
          offenders.add(path.relativePath(RepoRoot))
  for path in ["README.md", "coworld_manifest_template.json"]:
    if "/client/replay" in readFile(RepoRoot / path):
      offenders.add(path)
  check(offenders.len == 0,
    "no /client/replay pod path anywhere, found it in: " &
      offenders.join(", "))
  check(game{"runnable"}{"type"}.getStr() == "game",
    "game.runnable.type must be \"game\" (coworld 0.1.42)")
  check(game{"owner"}.getStr().len > 0, "game.owner is required")
  check(manifest{"episode_timeout_minutes"}.getInt() > 0,
    "episode_timeout_minutes is TOP-LEVEL")
  check(manifest{"version"} == nil, "there is no top-level version")
  check(game{"display_name"} == nil, "and no game.display_name")
  check(manifest{"$schema"}.getStr().len > 0, "$schema is required")
  check(manifest{"tags"}.len >= 3, "at least three tags")

block docsAndProtocols:
  let docs = game{"docs"}
  check(docs{"readme"}{"type"}.getStr() == "text",
    "docs.readme is a {type,value} TEXT object")
  check(docs{"readme"}{"value"}.getStr().len > 200,
    "and carries a real readme")
  check(docs{"pages"}.len >= 2, "at least two doc pages")
  for page in docs{"pages"}:
    check(page{"id"}.getStr().len > 0, "every page needs an id")
    check(page{"title"}.getStr().len > 0, "and a title")
    check(page{"content"}{"type"}.getStr() == "text",
      "and a TEXT content object")
    check(page{"content"}{"value"}.getStr().len > 200,
      "with a real value")
  let protocols = game{"protocols"}
  for key in ["player", "global"]:
    check(protocols{key} != nil, "game.protocols." & key & " is required")
    check(protocols{key}{"type"}.getStr() == "text",
      "game.protocols." & key & " must be a {type,value} object, not a bare " &
      "string (cogame-garble, 2026-08-24)")
    check(protocols{key}{"value"}.getStr().len > 200,
      "and carry a real value")

block schemaBounds:
  let schema = game{"config_schema"}
  check(schema{"additionalProperties"}.getBool() == false,
    "config_schema refuses unknown keys")
  var required: seq[string]
  for row in schema{"required"}:
    required.add(row.getStr())
  check("tokens" in required, "tokens is required")
  for key, value in schema{"properties"}.pairs:
    if value{"type"}.getStr() == "array":
      check(value{"minItems"} != nil and value{"maxItems"} != nil,
        "every ARRAY property needs minItems AND maxItems, " & key &
        " does not (tandem 0.1.0, 2026-08-23)")
  check(schema{"properties"}{"num_agents"}{"minimum"}.getInt() == Seats,
    "num_agents is pinned at " & $Seats)
  check(schema{"properties"}{"num_agents"}{"maximum"}.getInt() == Seats,
    "at both ends")

block resultsSchema:
  let schema = game{"results_schema"}
  var required: seq[string]
  for row in schema{"required"}:
    required.add(row.getStr())
  for key in ["names", "aliases", "roles", "scores", "win", "winner",
      "reason", "ending"]:
    check(key in required, "results_schema must require " & key)
  for key, value in schema{"properties"}.pairs:
    if value{"type"}.getStr() == "array":
      check(value{"minItems"}.getInt() == Seats and
        value{"maxItems"}.getInt() == Seats,
        "every results array is exactly " & $Seats & " long, " & key &
        " is not")
  var endings: seq[string]
  for row in schema{"properties"}{"ending"}{"enum"}:
    endings.add(row.getStr())
  check(endings.len == 6, "six legal endings")
  for ending in ["crew_deposits", "impostor_ejected", "impostor_isolation",
      "timeout", "deadline", "forfeit"]:
    check(ending in endings, ending & " must be a legal ending")

block certificationFitsItsTimeout:
  ## `coworld certify` defaults to --timeout-seconds 60 covering start +
  ## connect grace + the whole episode + post-game linger. Size it so
  ## grace + play + linger stays under 50 s (commons-family, 2026-08-24).
  let fixture = manifest{"certification"}{"game_config"}
  let maxTicks = fixture{"maxTicks"}.getInt()
  check(maxTicks > 0, "the fixture pins maxTicks")
  ## The sim is NOT wall-clock paced: the whole episode computes in a couple of
  ## seconds with every seat scripted and minBatchSeconds 0. What the certifier
  ## waits on is startup plus the shutdown grace.
  check(fixture{"minBatchSeconds"}.getInt() == 0,
    "the fixture must not pace its batches")
  let config = defaultGameConfig()
  let budget = 4.0 + maxTicks.float * 0.002 +
    config.shutdownGraceSeconds.float
  check(budget < 50.0,
    "startup + play + linger must stay under 50 s, computed " & $budget)
  ## And the replay it produces must outlast the 10 s viewer soak.
  check(maxTicks.float / TargetFps.float > 12.0,
    "the fixture replay must outlast the viewer soak, it is " &
    $(maxTicks.float / TargetFps.float) & " s")

block certificationSeatsTheLoudBaseline:
  ## `lurker` is pinned on the impostor slot so the fixture reliably produces a
  ## freeze, a witnessed freeze and a CAUGHT! banner.
  let cert = manifest{"certification"}
  let impostorSlot = cert{"game_config"}{"impostorSlot"}.getInt()
  check(impostorSlot >= 0 and impostorSlot < Seats,
    "the fixture pins the impostor slot")
  check(cert{"players"}[impostorSlot]{"player_id"}.getStr() ==
    "hidden-agenda-lurker",
    "the lurker must be seated on the pinned impostor slot")
  check(cert{"game_config"}{"chat"}.getBool() == false,
    "the fixture runs the no-talk shape, so both deliberation shapes are " &
    "exercised by CI")

block theCertificationEpisodeActuallyPlays:
  ## The fixture is not just a config: `docker_smoke.sh` runs it for real and
  ## `ci.yml`'s wasm-viewer job plays the replay it produces with `--soak 10`.
  ## A replay SHORTER than the soak window reports a finished playback as a
  ## frozen one (ecos, 2026-08-23), and a replay with no `caught` event never
  ## exercises the game's headline chrome (cogchemists, 2026-08-24). Both are
  ## properties of the EPISODE, not of the JSON, so play it.
  let fixture = manifest{"certification"}{"game_config"}
  var node = copy(fixture)
  node["tokens"] = %["t0", "t1", "t2", "t3", "t4"]
  var config = defaultGameConfig()
  config.update($node)
  var kinds: seq[ScriptKind]
  for row in manifest{"certification"}{"players"}:
    kinds.add(parseScriptKind(
      row{"player_id"}.getStr().replace("hidden-agenda-", "")))
  for kind in kinds:
    check(kind != skNone, "every certification seat names a real baseline")
  let episode = playEpisode(config, kinds)
  let seconds = episode.frames.len.float / TargetFps.float
  check(seconds > 12.0,
    "the certification replay must outlast the 10 s viewer soak, it is " &
    $seconds & " s (" & $episode.frames.len & " ticks)")
  check(episode.reason == "complete",
    "the fixture must end complete, got " & episode.reason)
  var caught = 0
  var freezes = 0
  var votes = 0
  for row in episode.log.rows:
    case row{"k"}.getStr()
    of "caught": caught.inc
    of "freeze": freezes.inc
    of "vote": votes.inc
    else: discard
  check(freezes >= 1, "the fixture must produce a freeze")
  check(caught >= 1,
    "and a WITNESSED one, so the CAUGHT! banner is exercised by CI")
  check(votes >= 1, "and a vote, so the vote board is exercised")
  check(episode.meetings.len >= 1, "and at least one meeting")

block everyVariantConstructs:
  ## Test EVERY variant's game_config, not just the fixture: a config-scaled
  ## mint that only the variants reach is invisible to a cert-fixture-only
  ## check (cogame-collab-cooking 0.1.1, 2026-08-25).
  for variant in manifest{"variants"}:
    var config = defaultGameConfig()
    var node = copy(variant{"game_config"})
    node["tokens"] = %["t0", "t1", "t2", "t3", "t4"]
    config.update($node)
    check(config.numAgents == Seats,
      variant{"id"}.getStr() & " constructs with five seats")
  var fixture = copy(manifest{"certification"}{"game_config"})
  fixture["tokens"] = %["t0", "t1", "t2", "t3", "t4"]
  var config = defaultGameConfig()
  config.update($fixture)
  check(config.numAgents == Seats, "and so does the certification fixture")
  check(config.playDeadlineSeconds() <= 720.0 + 1e-9,
    "the play deadline is 60% of episodeTimeoutSeconds")

echo "test_manifest: ok"
